/**
 * Copyright 2011 The Open Source Research Group,
 *                University of Erlangen-Nürnberg
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2011-04-13 23:18:40.
 */

package de.fau.cs.osr.ptk.printergen.parser;

import de.fau.cs.osr.ptk.common.ast.*;




/**
 * <h1>PrinterTemplate</h1>
 */
public class PrinterTemplate
        extends InnerNode.InnerNode2
        
{
	private static final long serialVersionUID = 1L;

	// =========================================================================

	public PrinterTemplate()
	{
		super(new Intro(), new NodeList());

	}
	public PrinterTemplate(Intro intro, NodeList templates)
	{
		super(intro, templates);

	}




	// =========================================================================
	// Properties




	// =========================================================================
	// Children

	public final void setIntro(Intro intro)
	{
		set(0, intro);
	}
	
	public final Intro getIntro()
	{
		return (Intro) get(0);
	}
	public final void setTemplates(NodeList templates)
	{
		set(1, templates);
	}
	
	public final NodeList getTemplates()
	{
		return (NodeList) get(1);
	}

	private static final String[] CHILD_NAMES = new String[] {"intro", "templates"};

	public final String[] getChildNames()
	{
		return CHILD_NAMES;
	}


	// =========================================================================


}
