/**
 * Copyright 2011 The Open Source Research Group,
 *                University of Erlangen-Nürnberg
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2011-04-13 17:41:42.
 */

package de.fau.cs.osr.ptk.nodegen.parser;

import de.fau.cs.osr.ptk.common.ast.AstNodeInterface;
import de.fau.cs.osr.ptk.common.ast.AstNodePropertyIterator;
import de.fau.cs.osr.ptk.common.ast.InnerNode;




/**
 * <h1>Section</h1>
 */
public class Section
        extends InnerNode.InnerNode1
        
{
	private static final long serialVersionUID = 1L;

	// =========================================================================

	public Section()
	{
		super((AstNodeInterface) null);

	}
	public Section(int level, String title, AstNodeInterface body)
	{
		super(body);
		setLevel(level);
		setTitle(title);

	}




	// =========================================================================
	// Properties

	private int level;

	public final int getLevel()
	{
		return this.level;
	}
	
	public final int setLevel(int level)
	{
		int old = this.level;
		this.level = level;
		return old;
	}
	private String title;

	public final String getTitle()
	{
		return this.title;
	}
	
	public final String setTitle(String title)
	{
		String old = this.title;
		this.title = title;
		return old;
	}

	@Override
	public final int getPropertyCount()
	{
		return 2;
	}
	
	@Override
	public final AstNodePropertyIterator propertyIterator()
	{
		return new AstNodePropertyIterator()
		{
			@Override
			protected int getPropertyCount()
			{
				return 2;
			}
			
			@Override
			protected String getName(int index)
			{
				switch (index)
				{
					case 0:
						return "level";
					case 1:
						return "title";

					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object getValue(int index)
			{
				switch (index)
				{
					case 0:
						return Section.this.getLevel();
					case 1:
						return Section.this.getTitle();

					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object setValue(int index, Object value)
			{
				switch (index)
				{
					case 0:
						return Section.this.setLevel((Integer) value);
					case 1:
						return Section.this.setTitle((String) value);

					default:
						throw new IndexOutOfBoundsException();
				}
			}
		};
	}


	// =========================================================================
	// Children

	public final void setBody(AstNodeInterface body)
	{
		set(0, body);
	}
	
	public final AstNodeInterface getBody()
	{
		return (AstNodeInterface) get(0);
	}

	private static final String[] CHILD_NAMES = new String[] {"body"};

	public final String[] getChildNames()
	{
		return CHILD_NAMES;
	}


	// =========================================================================


}
